% Create a circularArray with dipole element.
% Generated by MATLAB(R) 26.1 and Antenna Toolbox 26.1
%Generated on:06-Jul-2026 09:53:47

%% Array Properties 
clc;
d = design(dipole,1e9);
d.Conductor = metal('Copper');
arrayObject = circularArray;
arrayObject.Element = d;
arrayObject.NumElements = 8;
arrayObject.Radius = 0.3;    

%% Array Analysis 
% Show for circularArray
figure;
show(arrayObject) 
% Layout for circularArray
figure;
layout(arrayObject) 
% Pattern for circularArray
plotFrequency = 1*1e9; termination = 50;
figure;
pattern(arrayObject, plotFrequency); 
% Azimuth for circularArray
plotFrequency = 1*1e9; azRange = 0:5:360; termination = 50;
figure;
pattern(arrayObject, plotFrequency, azRange, 0);
% Elevation for circularArray
plotFrequency = 1*1e9; elRange = 0:5:360; termination = 50;
figure;
pattern(arrayObject, plotFrequency, 0, elRange);


bw = beamwidth(arrayObject,1e9, 0, 1:1:360);         % Beamwidth of dipole
fprintf('Beamwidth: %.2f degrees\n', bw(1));
fprintf('Number of Elements = %d\n',arrayObject.NumElements);
fprintf('Element Spacing = %.2f m\n',arrayObject.Radius);
