% Create a dipole antenna
% Generated by MATLAB(R) 26.1 and Antenna Toolbox 26.1
%Generated on:24-Jun-2026 15:59:05
clc
disp('Script Started')
antennaObject = design(dipole, 156.8*1e6); 
%% Antenna Properties 
figure;                                            % Show
show(antennaObject) 
%% Antenna Analysis         % Define plot frequency 
plotFrequency = 156.8*1e6;
freqRange = (141.12:0.5:172.48)*1e6;           % Define frequency range 
refImpedance = 50;              % Reference Impedance 
figure;          % sparameter
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)

bw = beamwidth(antennaObject, 156.8e6, 0, 1:1:360);         % Beamwidth of dipole
fprintf('Dipole Beamwidth: %.2f degrees\n', bw);

G = pattern(antennaObject,156.8e6,0,0,'Type','gain');      %Gain
disp(['Gain = ', num2str(G), ' dBi'])

D = pattern(antennaObject,156.8e6,0,0,'Type','directivity');     %Directivity
disp(['Directivity = ', num2str(D), ' dBi'])

