% Create a patchMicrostrip antenna
% Generated by MATLAB(R) 26.1 and Antenna Toolbox 26.1
%Generated on:01-Jul-2026 20:51:33
clc;
%% Antenna Properties 

antennaObject = design(patchMicrostrip, 900*1e6);
antennaObject.Conductor.Name = 'Copper';
antennaObject.Conductor.Conductivity = 5.96*1e7;
antennaObject.Conductor.Thickness = 3.556e-05;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
f=900e6;
plotFrequency = f;
% Define frequency range 
freqRange = (810:2:990)*1e6;
% Reference Impedance 
refImpedance = 50;
% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)% pattern
figure;
pattern(antennaObject, plotFrequency)% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

figure;
pattern(antennaObject,900e6,'Type','gain');

az = -180:2:180;
el = -90:2:90;

G = pattern(antennaObject,900e6,az,el,'Type','gain');
maxGain = max(G(:));

D = pattern(antennaObject,900e6,az,el,'Type','directivity');
maxDirectivity = max(D(:));

fprintf("Maximum Gain = %.2f dBi\n", maxGain);
fprintf("Maximum Directivity = %.2f dBi\n", maxDirectivity);

