% Create a monopole antenna
% Generated by MATLAB(R) 26.1 and Antenna Toolbox 26.1
%Generated on:24-Jun-2026 22:54:53
clc;                                         %% Antenna Properties 
antennaObject = design(monopole, 156.8e6);
figure;                                        % Show
show(antennaObject) 
plotFrequency = 156.8*1e6;        %% Antenna Analysis      % Define plot frequency 
freqRange = (141.12:0.5:172.48)*1e6;          % Define frequency range 
refImpedance = 50;             % Reference Impedance 
figure;                        % impedance
impedance(antennaObject, freqRange)         % sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)                                 % pattern
figure;
pattern(antennaObject, plotFrequency)         % elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

%% Dipole
dipoleObj = design(dipole,156.8e6);
dipoleGain = pattern(dipoleObj,156.8e6,0,0,'Type','gain');
Dipoledirectivity= pattern(dipoleObj,156.8e6,0,0,'Type','directivity');

%% Monopole
monopoleGain = pattern(antennaObject,156.8e6,0,0,'Type','gain');
fprintf('\nGain and Directivity Comparison of Dipole and Monopole\n');
monopoledirectivity= pattern(antennaObject,156.8e6,0,0,'Type','directivity');

fprintf('Dipole Gain   : %.3f dBi\n',dipoleGain);
fprintf('Monopole Gain : %.3f dBi\n',monopoleGain);

fprintf('Dipole directivity   : %.3f dBi\n',Dipoledirectivity);
fprintf('Monopole directivity : %.3f dBi\n',monopoledirectivity);