% Create a yagiUda antenna
% Generated by MATLAB(R) 26.1 and Antenna Toolbox 26.1
%Generated on:02-Jul-2026 11:16:02

%% Antenna Properties 
clc;
antennaObject = design(yagiUda, 1000*1e6);
antennaObject.Exciter= dipoleFolded;


antennaObject.Exciter.Length = 0.13065;
antennaObject.Exciter.Width = 0.0033277;
antennaObject.Exciter.Spacing = 0.0017088;
antennaObject.NumDirectors = 3;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 1*1e9;
% Define frequency range 
freqRange = (900:2:1100)*1e6;
% Reference Impedance 
refImpedance = 50;
% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)% pattern
figure;
pattern(antennaObject, plotFrequency)% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

bw = beamwidth(antennaObject, 1e9, 0, 1:1:360);         % Beamwidth of dipole
fprintf('Dipole Beamwidth: %.2f degrees\n', bw);

figure;
pattern(antennaObject,900e6,'Type','gain');
el = -90:1:90;
G = pattern(antennaObject,1e9,0,el,'Type','gain');
[maxGain,idx] = max(G);
forwardEl = el(idx);
backEl = -forwardEl;
[~,backIdx] = min(abs(el-backEl));
backGain = G(backIdx);
FB = maxGain - backGain;
fprintf("Forward Gain = %.2f dBi\n",maxGain);
fprintf("Backward Gain = %.2f dBi\n",backGain);
fprintf("Front-to-Back Ratio = %.2f dB\n",FB);